name: helixworlds_snatcher_sdk
description: Image Labeling Technology provided by metaversegroup
homepage: https://www.helixworlds.com/
documentation: https://github.com/MetaverseGroup/helixworlds-snatcher-sdk
platforms:
  android:
  ios:

topics:
  - imagelabeling
  - metaverse


version: 1.0.3+6


environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  google_mlkit_image_labeling: ^0.9.0
  aws_rekognition_api: ^2.0.0
  path_provider: ^2.1.1
  path: ^1.8.3
  url_launcher: ^6.1.14
  sentry_flutter: ^7.10.1

  provider: ^6.0.2
  equatable: ^2.0.3
  rxdart: ^0.26.0
  freezed_annotation: ^2.4.1
  dio: ^4.0.4
  json_annotation: ^4.4.0
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.8
  dartz: ^0.10.1
  go_router: ^5.2.0
  simple_connection_checker: ^0.2.1
  get_it: ^7.2.0
  mixpanel_flutter: ^2.2.0
  firebase_analytics: ^10.8.0

  cached_network_image: ^3.2.0



dev_dependencies:
  # flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: any
  build_runner: any
  json_serializable: any
  mockito: any
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true

