// Mocks generated by Mockito 5.4.4 from annotations
// in helixworlds_snatcher_sdk/test/features/scan/data/scan_screen_remote_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:dartz/dartz.dart' as _i7;
import 'package:dio/dio.dart' as _i8;
import 'package:dio/src/adapter.dart' as _i3;
import 'package:dio/src/cancel_token.dart' as _i10;
import 'package:dio/src/dio_mixin.dart' as _i5;
import 'package:dio/src/options.dart' as _i2;
import 'package:dio/src/response.dart' as _i6;
import 'package:dio/src/transformer.dart' as _i4;
import 'package:helixworlds_snatcher_sdk/core/failure.dart' as _i12;
import 'package:helixworlds_snatcher_sdk/core/success.dart' as _i16;
import 'package:helixworlds_snatcher_sdk/features/log/data/model/log_model.dart'
    as _i15;
import 'package:helixworlds_snatcher_sdk/features/scan/data/model/scan_model.dart'
    as _i13;
import 'package:helixworlds_snatcher_sdk/features/scan/data/scan_local_datasource.dart'
    as _i19;
import 'package:helixworlds_snatcher_sdk/features/scan/data/scan_remote_datasource.dart'
    as _i11;
import 'package:helixworlds_snatcher_sdk/utils/helper_util.dart' as _i17;
import 'package:image_picker/image_picker.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseOptions_0 extends _i1.SmartFake implements _i2.BaseOptions {
  _FakeBaseOptions_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientAdapter_1 extends _i1.SmartFake
    implements _i3.HttpClientAdapter {
  _FakeHttpClientAdapter_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransformer_2 extends _i1.SmartFake implements _i4.Transformer {
  _FakeTransformer_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInterceptors_3 extends _i1.SmartFake implements _i5.Interceptors {
  _FakeInterceptors_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_4<T1> extends _i1.SmartFake implements _i6.Response<T1> {
  _FakeResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_5<L, R> extends _i1.SmartFake implements _i7.Either<L, R> {
  _FakeEither_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i8.Dio {
  @override
  _i2.BaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeBaseOptions_0(
          this,
          Invocation.getter(#options),
        ),
        returnValueForMissingStub: _FakeBaseOptions_0(
          this,
          Invocation.getter(#options),
        ),
      ) as _i2.BaseOptions);

  @override
  set options(_i2.BaseOptions? _options) => super.noSuchMethod(
        Invocation.setter(
          #options,
          _options,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
        Invocation.getter(#httpClientAdapter),
        returnValue: _FakeHttpClientAdapter_1(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
        returnValueForMissingStub: _FakeHttpClientAdapter_1(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
      ) as _i3.HttpClientAdapter);

  @override
  set httpClientAdapter(_i3.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(
          #httpClientAdapter,
          _httpClientAdapter,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Transformer get transformer => (super.noSuchMethod(
        Invocation.getter(#transformer),
        returnValue: _FakeTransformer_2(
          this,
          Invocation.getter(#transformer),
        ),
        returnValueForMissingStub: _FakeTransformer_2(
          this,
          Invocation.getter(#transformer),
        ),
      ) as _i4.Transformer);

  @override
  set transformer(_i4.Transformer? _transformer) => super.noSuchMethod(
        Invocation.setter(
          #transformer,
          _transformer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Interceptors get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: _FakeInterceptors_3(
          this,
          Invocation.getter(#interceptors),
        ),
        returnValueForMissingStub: _FakeInterceptors_3(
          this,
          Invocation.getter(#interceptors),
        ),
      ) as _i5.Interceptors);

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<_i6.Response<T>> get<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> getUri<T>(
    Uri? uri, {
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [uri],
          {
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> post<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> postUri<T>(
    Uri? uri, {
    dynamic data,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> put<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> putUri<T>(
    Uri? uri, {
    dynamic data,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> head<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> headUri<T>(
    Uri? uri, {
    dynamic data,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #headUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> delete<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> deleteUri<T>(
    Uri? uri, {
    dynamic data,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> patch<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> patchUri<T>(
    Uri? uri, {
    dynamic data,
    _i2.Options? options,
    _i10.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  void lock() => super.noSuchMethod(
        Invocation.method(
          #lock,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unlock() => super.noSuchMethod(
        Invocation.method(
          #unlock,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<_i6.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i10.CancelToken? cancelToken,
    bool? deleteOnError = true,
    String? lengthHeader = r'content-length',
    dynamic data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            urlPath,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i9.Future<_i6.Response<dynamic>>.value(_FakeResponse_4<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Response<dynamic>>.value(_FakeResponse_4<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<dynamic>>);

  @override
  _i9.Future<_i6.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    _i10.CancelToken? cancelToken,
    bool? deleteOnError = true,
    String? lengthHeader = r'content-length',
    dynamic data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUri,
          [
            uri,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i9.Future<_i6.Response<dynamic>>.value(_FakeResponse_4<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Response<dynamic>>.value(_FakeResponse_4<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<dynamic>>);

  @override
  _i9.Future<_i6.Response<T>> request<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i10.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #request,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #request,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> requestUri<T>(
    Uri? uri, {
    dynamic data,
    _i10.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUri,
          [uri],
          {
            #data: data,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);

  @override
  _i9.Future<_i6.Response<T>> fetch<T>(_i2.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [requestOptions],
        ),
        returnValue: _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
      ) as _i9.Future<_i6.Response<T>>);
}

/// A class which mocks [IScanRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIScanRemoteDatasource extends _i1.Mock
    implements _i11.IScanRemoteDatasource {
  @override
  _i9.Future<
      _i7.Either<_i12.Failure, _i13.InventoryItemModel>> getInventoryItemByID(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInventoryItemByID,
          [id],
        ),
        returnValue:
            _i9.Future<_i7.Either<_i12.Failure, _i13.InventoryItemModel>>.value(
                _FakeEither_5<_i12.Failure, _i13.InventoryItemModel>(
          this,
          Invocation.method(
            #getInventoryItemByID,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Either<_i12.Failure, _i13.InventoryItemModel>>.value(
                _FakeEither_5<_i12.Failure, _i13.InventoryItemModel>(
          this,
          Invocation.method(
            #getInventoryItemByID,
            [id],
          ),
        )),
      ) as _i9.Future<_i7.Either<_i12.Failure, _i13.InventoryItemModel>>);

  @override
  _i9.Future<_i7.Either<_i12.Failure, String>> objectScanned(
    _i14.XFile? photo,
    String? accessToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #objectScanned,
          [
            photo,
            accessToken,
          ],
        ),
        returnValue: _i9.Future<_i7.Either<_i12.Failure, String>>.value(
            _FakeEither_5<_i12.Failure, String>(
          this,
          Invocation.method(
            #objectScanned,
            [
              photo,
              accessToken,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Either<_i12.Failure, String>>.value(
                _FakeEither_5<_i12.Failure, String>(
          this,
          Invocation.method(
            #objectScanned,
            [
              photo,
              accessToken,
            ],
          ),
        )),
      ) as _i9.Future<_i7.Either<_i12.Failure, String>>);

  @override
  _i9.Future<_i7.Either<_i12.Failure, _i13.InventoryItemModel>> objectScannedV2(
    _i14.XFile? photo,
    String? accessToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #objectScannedV2,
          [
            photo,
            accessToken,
          ],
        ),
        returnValue:
            _i9.Future<_i7.Either<_i12.Failure, _i13.InventoryItemModel>>.value(
                _FakeEither_5<_i12.Failure, _i13.InventoryItemModel>(
          this,
          Invocation.method(
            #objectScannedV2,
            [
              photo,
              accessToken,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Either<_i12.Failure, _i13.InventoryItemModel>>.value(
                _FakeEither_5<_i12.Failure, _i13.InventoryItemModel>(
          this,
          Invocation.method(
            #objectScannedV2,
            [
              photo,
              accessToken,
            ],
          ),
        )),
      ) as _i9.Future<_i7.Either<_i12.Failure, _i13.InventoryItemModel>>);

  @override
  _i9.Future<_i7.Either<_i12.Failure, _i13.ScanResponseModel>> objectScannedV4(
    _i14.XFile? photo,
    String? accessToken, {
    String? email,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #objectScannedV4,
          [
            photo,
            accessToken,
          ],
          {#email: email},
        ),
        returnValue:
            _i9.Future<_i7.Either<_i12.Failure, _i13.ScanResponseModel>>.value(
                _FakeEither_5<_i12.Failure, _i13.ScanResponseModel>(
          this,
          Invocation.method(
            #objectScannedV4,
            [
              photo,
              accessToken,
            ],
            {#email: email},
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Either<_i12.Failure, _i13.ScanResponseModel>>.value(
                _FakeEither_5<_i12.Failure, _i13.ScanResponseModel>(
          this,
          Invocation.method(
            #objectScannedV4,
            [
              photo,
              accessToken,
            ],
            {#email: email},
          ),
        )),
      ) as _i9.Future<_i7.Either<_i12.Failure, _i13.ScanResponseModel>>);

  @override
  _i9.Future<_i7.Either<_i12.Failure, _i13.ScanResponseModel>> objectScannedV5(
    _i14.XFile? photo,
    String? accessToken, {
    String? email,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #objectScannedV5,
          [
            photo,
            accessToken,
          ],
          {#email: email},
        ),
        returnValue:
            _i9.Future<_i7.Either<_i12.Failure, _i13.ScanResponseModel>>.value(
                _FakeEither_5<_i12.Failure, _i13.ScanResponseModel>(
          this,
          Invocation.method(
            #objectScannedV5,
            [
              photo,
              accessToken,
            ],
            {#email: email},
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Either<_i12.Failure, _i13.ScanResponseModel>>.value(
                _FakeEither_5<_i12.Failure, _i13.ScanResponseModel>(
          this,
          Invocation.method(
            #objectScannedV5,
            [
              photo,
              accessToken,
            ],
            {#email: email},
          ),
        )),
      ) as _i9.Future<_i7.Either<_i12.Failure, _i13.ScanResponseModel>>);

  @override
  _i9.Future<_i7.Either<_i12.Failure, _i13.ScanResponseModel>> objectScannedV6(
    _i14.XFile? photo,
    String? accessToken, {
    String? email,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #objectScannedV6,
          [
            photo,
            accessToken,
          ],
          {#email: email},
        ),
        returnValue:
            _i9.Future<_i7.Either<_i12.Failure, _i13.ScanResponseModel>>.value(
                _FakeEither_5<_i12.Failure, _i13.ScanResponseModel>(
          this,
          Invocation.method(
            #objectScannedV6,
            [
              photo,
              accessToken,
            ],
            {#email: email},
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Either<_i12.Failure, _i13.ScanResponseModel>>.value(
                _FakeEither_5<_i12.Failure, _i13.ScanResponseModel>(
          this,
          Invocation.method(
            #objectScannedV6,
            [
              photo,
              accessToken,
            ],
            {#email: email},
          ),
        )),
      ) as _i9.Future<_i7.Either<_i12.Failure, _i13.ScanResponseModel>>);

  @override
  _i9.Future<_i7.Either<_i12.Failure, List<_i15.MyLogModel>>> getMySavedScans(
          String? accessToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMySavedScans,
          [accessToken],
        ),
        returnValue:
            _i9.Future<_i7.Either<_i12.Failure, List<_i15.MyLogModel>>>.value(
                _FakeEither_5<_i12.Failure, List<_i15.MyLogModel>>(
          this,
          Invocation.method(
            #getMySavedScans,
            [accessToken],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Either<_i12.Failure, List<_i15.MyLogModel>>>.value(
                _FakeEither_5<_i12.Failure, List<_i15.MyLogModel>>(
          this,
          Invocation.method(
            #getMySavedScans,
            [accessToken],
          ),
        )),
      ) as _i9.Future<_i7.Either<_i12.Failure, List<_i15.MyLogModel>>>);

  @override
  _i9.Future<_i7.Either<_i12.Failure, _i15.MyLogModel>> newSavedScans(
    String? token,
    _i15.MyLogModel? model,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #newSavedScans,
          [
            token,
            model,
          ],
        ),
        returnValue:
            _i9.Future<_i7.Either<_i12.Failure, _i15.MyLogModel>>.value(
                _FakeEither_5<_i12.Failure, _i15.MyLogModel>(
          this,
          Invocation.method(
            #newSavedScans,
            [
              token,
              model,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Either<_i12.Failure, _i15.MyLogModel>>.value(
                _FakeEither_5<_i12.Failure, _i15.MyLogModel>(
          this,
          Invocation.method(
            #newSavedScans,
            [
              token,
              model,
            ],
          ),
        )),
      ) as _i9.Future<_i7.Either<_i12.Failure, _i15.MyLogModel>>);

  @override
  _i9.Future<_i7.Either<_i12.Failure, _i16.Success>> deleteSavedScans(
    String? token,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSavedScans,
          [
            token,
            id,
          ],
        ),
        returnValue: _i9.Future<_i7.Either<_i12.Failure, _i16.Success>>.value(
            _FakeEither_5<_i12.Failure, _i16.Success>(
          this,
          Invocation.method(
            #deleteSavedScans,
            [
              token,
              id,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Either<_i12.Failure, _i16.Success>>.value(
                _FakeEither_5<_i12.Failure, _i16.Success>(
          this,
          Invocation.method(
            #deleteSavedScans,
            [
              token,
              id,
            ],
          ),
        )),
      ) as _i9.Future<_i7.Either<_i12.Failure, _i16.Success>>);
}

/// A class which mocks [HelperUtil].
///
/// See the documentation for Mockito's code generation for more information.
class MockHelperUtil extends _i1.Mock implements _i17.HelperUtil {
  @override
  _i9.Future<_i7.Either<_i12.Failure, _i16.Success>> redirectUrl(
    _i13.InventoryItemModel? model, {
    String? accessToken = r'',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #redirectUrl,
          [model],
          {#accessToken: accessToken},
        ),
        returnValue: _i9.Future<_i7.Either<_i12.Failure, _i16.Success>>.value(
            _FakeEither_5<_i12.Failure, _i16.Success>(
          this,
          Invocation.method(
            #redirectUrl,
            [model],
            {#accessToken: accessToken},
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Either<_i12.Failure, _i16.Success>>.value(
                _FakeEither_5<_i12.Failure, _i16.Success>(
          this,
          Invocation.method(
            #redirectUrl,
            [model],
            {#accessToken: accessToken},
          ),
        )),
      ) as _i9.Future<_i7.Either<_i12.Failure, _i16.Success>>);

  @override
  _i9.Future<void> launchUrlWithHeaders(
    _i13.InventoryItemModel? item,
    String? accessToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #launchUrlWithHeaders,
          [
            item,
            accessToken,
          ],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  String formatDate(String? dateString) => (super.noSuchMethod(
        Invocation.method(
          #formatDate,
          [dateString],
        ),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #formatDate,
            [dateString],
          ),
        ),
        returnValueForMissingStub: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #formatDate,
            [dateString],
          ),
        ),
      ) as String);

  @override
  String getDateString() => (super.noSuchMethod(
        Invocation.method(
          #getDateString,
          [],
        ),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #getDateString,
            [],
          ),
        ),
        returnValueForMissingStub: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #getDateString,
            [],
          ),
        ),
      ) as String);

  @override
  _i9.Future<_i7.Either<_i12.Failure, _i6.Response<dynamic>>> getRequest(
    _i8.Dio? dio,
    String? url,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRequest,
          [
            dio,
            url,
          ],
        ),
        returnValue:
            _i9.Future<_i7.Either<_i12.Failure, _i6.Response<dynamic>>>.value(
                _FakeEither_5<_i12.Failure, _i6.Response<dynamic>>(
          this,
          Invocation.method(
            #getRequest,
            [
              dio,
              url,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Either<_i12.Failure, _i6.Response<dynamic>>>.value(
                _FakeEither_5<_i12.Failure, _i6.Response<dynamic>>(
          this,
          Invocation.method(
            #getRequest,
            [
              dio,
              url,
            ],
          ),
        )),
      ) as _i9.Future<_i7.Either<_i12.Failure, _i6.Response<dynamic>>>);

  @override
  String getUrl(String? item) => (super.noSuchMethod(
        Invocation.method(
          #getUrl,
          [item],
        ),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #getUrl,
            [item],
          ),
        ),
        returnValueForMissingStub: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #getUrl,
            [item],
          ),
        ),
      ) as String);

  @override
  String getTitle(String? item) => (super.noSuchMethod(
        Invocation.method(
          #getTitle,
          [item],
        ),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #getTitle,
            [item],
          ),
        ),
        returnValueForMissingStub: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #getTitle,
            [item],
          ),
        ),
      ) as String);

  @override
  String getId(String? item) => (super.noSuchMethod(
        Invocation.method(
          #getId,
          [item],
        ),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #getId,
            [item],
          ),
        ),
        returnValueForMissingStub: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #getId,
            [item],
          ),
        ),
      ) as String);

  @override
  String getGame(String? item) => (super.noSuchMethod(
        Invocation.method(
          #getGame,
          [item],
        ),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #getGame,
            [item],
          ),
        ),
        returnValueForMissingStub: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #getGame,
            [item],
          ),
        ),
      ) as String);

  @override
  String getImage(String? item) => (super.noSuchMethod(
        Invocation.method(
          #getImage,
          [item],
        ),
        returnValue: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #getImage,
            [item],
          ),
        ),
        returnValueForMissingStub: _i18.dummyValue<String>(
          this,
          Invocation.method(
            #getImage,
            [item],
          ),
        ),
      ) as String);
}

/// A class which mocks [IScanLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIScanLocalDatasource extends _i1.Mock
    implements _i19.IScanLocalDatasource {
  @override
  _i9.Future<_i7.Either<_i12.Failure, _i16.Success>> cacheInventoryItem(
          _i13.InventoryItemModel? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheInventoryItem,
          [items],
        ),
        returnValue: _i9.Future<_i7.Either<_i12.Failure, _i16.Success>>.value(
            _FakeEither_5<_i12.Failure, _i16.Success>(
          this,
          Invocation.method(
            #cacheInventoryItem,
            [items],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Either<_i12.Failure, _i16.Success>>.value(
                _FakeEither_5<_i12.Failure, _i16.Success>(
          this,
          Invocation.method(
            #cacheInventoryItem,
            [items],
          ),
        )),
      ) as _i9.Future<_i7.Either<_i12.Failure, _i16.Success>>);

  @override
  _i9.Future<
      _i7.Either<_i12.Failure, _i13.InventoryItemModel>> fetchInventoryItemByID(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchInventoryItemByID,
          [id],
        ),
        returnValue:
            _i9.Future<_i7.Either<_i12.Failure, _i13.InventoryItemModel>>.value(
                _FakeEither_5<_i12.Failure, _i13.InventoryItemModel>(
          this,
          Invocation.method(
            #fetchInventoryItemByID,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Either<_i12.Failure, _i13.InventoryItemModel>>.value(
                _FakeEither_5<_i12.Failure, _i13.InventoryItemModel>(
          this,
          Invocation.method(
            #fetchInventoryItemByID,
            [id],
          ),
        )),
      ) as _i9.Future<_i7.Either<_i12.Failure, _i13.InventoryItemModel>>);

  @override
  _i9.Future<_i7.Either<_i12.Failure, List<_i13.InventoryItemModel>>>
      getInventoryItems() => (super.noSuchMethod(
            Invocation.method(
              #getInventoryItems,
              [],
            ),
            returnValue: _i9.Future<
                    _i7
                    .Either<_i12.Failure, List<_i13.InventoryItemModel>>>.value(
                _FakeEither_5<_i12.Failure, List<_i13.InventoryItemModel>>(
              this,
              Invocation.method(
                #getInventoryItems,
                [],
              ),
            )),
            returnValueForMissingStub: _i9.Future<
                    _i7
                    .Either<_i12.Failure, List<_i13.InventoryItemModel>>>.value(
                _FakeEither_5<_i12.Failure, List<_i13.InventoryItemModel>>(
              this,
              Invocation.method(
                #getInventoryItems,
                [],
              ),
            )),
          ) as _i9
              .Future<_i7.Either<_i12.Failure, List<_i13.InventoryItemModel>>>);
}
